ATRS/Controllers/PassengerController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATRS.Controllers
{
    public class PassengerController : Controller
    {
        atrsEntities ctx = new atrsEntities();
        // GET: Passenger
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PassengerList() 
        {
            var res = ctx.Database.SqlQuery<Passenger>("select * from passenger").ToList<Passenger>();
            return View(res);
        }
        public ActionResult AddPassenger(Passenger passenger) 
        {
            if (passenger != null) 
            {
                return View(passenger);
            }
            return View();
        }
        [HttpPost]
        public ActionResult AddPassengerToDB(Passenger passenger) 
        {
            if (passenger.PassengerID > 0)
            {
                var updateQuery = ("update Passenger set PassengerName =" + "\'" + passenger.PassengerName + "\'," + "PassportNo = '" + passenger.PassportNo + "\' ,MobileNo = " + passenger.MobileNo + "where PassengerID =" + passenger.PassengerID);
                ctx.Database.ExecuteSqlCommand(updateQuery);
                ctx.SaveChanges();
            }
            else
            { 
                var res = ctx.Database.SqlQuery<Passenger>("select * from passenger order by PassengerID desc").ToList<Passenger>();
                var passengerID = res[0].PassengerID + 1 ;
                var query = ("insert into passenger(PassengerID, PassengerName, PassportNo, MobileNo) values(" + passengerID + ",\'" + passenger.PassengerName + "\',\'" + passenger.PassportNo + "\'," + passenger.MobileNo + ")");
                ctx.Database.ExecuteSqlCommand(query);
                ctx.SaveChanges();
            }
            var resUpdated = ctx.Database.SqlQuery<Passenger>("select * from passenger").ToList<Passenger>();
            return View("PassengerList", resUpdated);
        }
        public ActionResult PassengerHistory()
        {
            return View();
        }
        public ActionResult UpdatePassenger() 
        { 
            return View(); 
        }
        public ActionResult DeletePassenger(int PassengerID) 
        {
            var query = ("delete from passenger where PassengerID=" + PassengerID);
            ctx.Database.ExecuteSqlCommand(query);
            ctx.SaveChanges();
            var resUpdated = ctx.Database.SqlQuery<Passenger>("select * from passenger").ToList<Passenger>();
            return View("PassengerList", resUpdated);
        }
    }
}

ATRS/Controllers/ReservationController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATRS.Controllers
{
    public class ReservationController : Controller
    {
        atrsEntities ctx = new atrsEntities();
        public ActionResult Reservations() 
        {
            var res = ctx.Database.SqlQuery<Reservation>("select * from Reservation").ToList<Reservation>();
            return View(res);
        }
        // GET: Reservation
        public ActionResult Book(Flight fDetials)
        {
            TempData["FlightNumber"] = fDetials.FlightNumber;
            TempData["FlightOrigin"] = fDetials.Origin;
            TempData["FlightDestination"] = fDetials.Destination;
            TempData["Layover"] = fDetials.Layover;
            var query = "select * from passenger";
            var res = ctx.Database.SqlQuery<Passenger>(query).ToList<Passenger>();
            return View(res);
        }

        [HttpPost]
        public ActionResult ConfirmBooking(FormCollection form) 
        {
            string flightNumber = form["FlightNumber"];
            string PassengerID = form["PassengerID"];
            string Ticket = form["Ticket"];
            var res = ctx.Database.SqlQuery<Reservation>("select * from Reservation order by ReservationNumber desc").ToList<Reservation>();
            var reservationID = res[0].ReservationNumber;
            reservationID += 1;
            var queryToReservation = ("insert into Reservation(ReservationNumber, PassengerID, Ticket, FlightNumber) values(" + reservationID + ",\'" + PassengerID + "\'," + "\'" + Ticket + "\'," + "\'" + flightNumber + "\')");
            ctx.Database.ExecuteSqlCommand(queryToReservation);
            ctx.SaveChanges();
            var resUpdated = ctx.Database.SqlQuery<Reservation>("select * from Reservation").ToList<Reservation>();
            return View("Reservations", resUpdated);
        }
    }
}

ATRS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ATRS Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Flight", "FlightSearch", "Flight")</li>
                    <li>@Html.ActionLink("Reservations", "Reservations", "Reservation")</li>
                    <li>@Html.ActionLink("Passengers", "PassengerList", "Passenger")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>