ATRS/Models/TravelHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ATRS.Models
{
    public class TravelHistory
    {
        public int PassengerID { get; set; }
        public string PassengerName { get; set; }
        public string PassportNo { get; set; }
        public string Ticket { get; set; }
        public string FlightNumber { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
    }
}

ATRS/Controllers/FlightTrackController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATRS.Models;

namespace ATRS.Controllers
{
    public class FlightTrackController : Controller
    {
        atrsEntities ctx = new atrsEntities();
        // GET: FlightTrack
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MostVisitedCity()
        {
            //ctx.MostVisitedCityGenerate();
            ViewBag.CityName = "No City Found";
            var query = "select TOP 1 FlightNumber, count(FlightNumber) as countFlight from FlightTrack where FlightDate > dateadd(month, -1, sysdatetime()) group by FlightNumber order by countFlight desc; ";
            var res = ctx.Database.SqlQuery<MostVisited>(query).ToList();
            if (res.Count > 0) { 
                var queryForCity = "select * from Flight where FlightNumber ="+"\'"+res[0].FlightNumber+"\'";
                var resCity = ctx.Database.SqlQuery<Flight>(queryForCity).ToList<Flight>();
                ViewBag.CityName = resCity[0].Destination;
            }
            return View();
        }
    }
}

ATRS/Controllers/HomeController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATRS.Models;

namespace ATRS.Controllers
{
    public class HomeController : Controller
    {
        atrsEntities ctx = new atrsEntities();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult PFDetails()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PFDetailsView(FormCollection form)
        {
            var reservationNumber = form["ReservationNumber"];
            var reservationResult = ctx.Database.SqlQuery<Reservation>("Select * from Reservation where ReservationNumber=" + reservationNumber).ToList<Reservation>();
            var passengerID = reservationResult[0].PassengerID;
            var flightNumber = reservationResult[0].FlightNumber;
            var passengerResult = ctx.Database.SqlQuery<Passenger>("select * from Passenger where PassengerID=" + passengerID).ToList<Passenger>();
            var flightResult = ctx.Database.SqlQuery<Flight>("Select * from Flight where FlightNumber=\'" + flightNumber+"\'").ToList<Flight>();
            TempData["PName"] = passengerResult[0].PassengerName;
            TempData["Ppassport"] = passengerResult[0].PassportNo;
            TempData["PMobile"] = passengerResult[0].MobileNo;
            TempData["FName"] = flightResult[0].Airline;
            TempData["FSource"] = flightResult[0].Origin;
            TempData["FDestination"] = flightResult[0].Destination;
            TempData["FStart"] = flightResult[0].Startdatetime;
            TempData["FLayover"] = "None";
            if (flightResult[0].Layover != null) 
            { 
                TempData["FLayover"] = flightResult[0].Layover;
            }
            //var travelTime = (flightResult[0].Enddatetime - flightResult[0].Startdatetime);
            //var totalHours = travelTime.TotalHours;
            TempData["JourneyTime"] = flightResult[0].Enddatetime - flightResult[0].Startdatetime;
            TempData["id"] = reservationNumber;
            return View();
        }

        public ActionResult TravelHistory() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult TravelHistoryView(FormCollection form) 
        {
            var passsengerName = form["PassengerName"];
            var passportNo = form["PassportNo"];
            //TempData["passport"] = passportNo;
            var query = @"Select Passenger.PassengerID ,Passenger.PassengerName,Passenger.PassportNo,Reservation.Ticket,
                        Flight.FlightNumber,Flight.Origin,Flight.Destination
                        from Passenger inner join Reservation on Passenger.PassengerID = Reservation.PassengerID
                        inner join Flight on Reservation.FlightNumber = Flight.FlightNumber
                        where Passenger.PassengerName = '" + passsengerName +"\'" + "and PassportNo = '" +passportNo + "\'";
            var res = ctx.Database.SqlQuery<TravelHistory>(query).ToList<TravelHistory>();
            return View(res);
        }

        public ActionResult TotalAicraft() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult TotalAicraftView(FormCollection form) 
        {
            var airLine = form["AirLineName"];
            var query = "select * from flight where lower(airline) = \'" +airLine.ToLower()+"\'";
            var res = ctx.Database.SqlQuery<Flight>(query).ToList<Flight>();
            TempData["countOfAirline"] = res.Count;
            TempData["airLineName"] = airLine;
            return View();
        }
    }
}

ATRS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ATRS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ATRS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Imp Links:</h2>
<h3>
    @Html.ActionLink("Get total number of aircrafts owned by a airline.", "TotalAicraft", "Home")
</h3>

<h3>
    @Html.ActionLink("Travel History for a Passenger.", "TravelHistory", "Home")
</h3>
<h3>
    @Html.ActionLink("Most Visited City in the last Month.", "MostVisitedCity", "FlightTrack")
</h3>
<h3>
    @Html.ActionLink("Get Passenger And Flight Details With Reservation Number.", "PFDetails", "Home")
</h3>

ATRS/Views/Home/PFDetails.cshtml
@{
    ViewBag.Title = "PFDetails";
}

<h2>Provide Reservation number to get the details.</h2>

@using (Html.BeginForm("PFDetailsView", "Home", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            <label>Reservation Number</label>
            <input type="text" name="ReservationNumber" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-default">Submit</button>
        </div>
    </div>
}
@Html.ActionLink("Back to Home", "Index", "Home")

ATRS/Views/Home/PFDetailsView.cshtml
@{
    ViewBag.Title = "PFDetailsView";
}

<h2>Details as per ReservationID: @TempData["id"]</h2>
<h4>Passenger Name: @TempData["PName"]</h4>
<h4>
    Passport NUmber: @TempData["Ppassport"]
</h4>
<h4>
    Mobile Number: @TempData["PMobile"]
</h4>
<h4>
    Flight Name: @TempData["FName"]
</h4>
<h4>
    Source: @TempData["FSource"]
</h4>
<h4>
    Destination: @TempData["FDestination"]
</h4>
<h4>
    Flight Start Time: @TempData["FStart"]
</h4>
<h4>
    Layover: @TempData["FLayover"]
</h4>
<h4>
    Total Travel Time: @TempData["JourneyTime"]
</h4>
@Html.ActionLink("Back to Home", "Index", "Home")

ATRS/Views/Home/TotalAicraft.cshtml
@{
    ViewBag.Title = "TotalAicraft";
}

<h2>Air Line Name</h2>

@using (Html.BeginForm("TotalAicraftView", "Home", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            <label>Air Line Name</label>
            <input type="text" name="AirLineName" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-default">Submit</button>
        </div>
    </div>
}
@Html.ActionLink("Back to Home", "Index", "Home")

ATRS/Views/Home/TotalAicraftView.cshtml
@{
    ViewBag.Title = "TotalAicraftView";
}

<h3>
    Total Number of aircrafts owned by @TempData["airLineName"] is: @TempData["countOfAirline"]
</h3>

@Html.ActionLink("Back to Home", "Index", "Home")

ATRS/Views/Home/TravelHistory.cshtml
@{
    ViewBag.Title = "TravelHistory";
}

<h2>TravelHistory</h2>

@using (Html.BeginForm("TravelHistoryView", "Home", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            <label>Passenger Name</label>
            <input type="text" name="PassengerName" class="form-control">
        </div>
        <div class="form-group">
            <label>Passport Number</label>
            <input type="text" name="PassportNo" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-default">Submit</button>
        </div>
    </div>
}
@Html.ActionLink("Back to Home", "Index", "Home")

ATRS/Views/Home/TravelHistoryView.cshtml
@model List<ATRS.Models.TravelHistory>
@{
    ViewBag.Title = "TravelHistoryView";
}

<h2>Travel History</h2>

<table class="table table-hover">
    <tr>
        <th>Flight Number</th>
        <th>Passenger ID</th>
        <th>Passenger Name</th>
        <th>Passport Number</th>
        <th>Origin</th>
        <th>Destination</th>
        <th>Ticket</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FlightNumber</td>
            <td>@item.PassengerID</td>
            <td>@item.PassengerName</td>
            <td>@item.PassportNo</td>
            <td>@item.Origin</td>
            <td>@item.Destination</td>
            <td>@item.Ticket</td>
        </tr>
    }
</table>

@Html.ActionLink("Back to Home", "Index", "Home")