ATRS/Controllers/FlightController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATRS.Controllers
{
    public class FlightController : Controller
    {
        // GET: Flight
        atrsEntities ctx = new atrsEntities();

        public ActionResult FlightSearch()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FlightList(Flight model)
        {
            var date = model.Startdatetime.ToString();
            var dateInput = Convert.ToDateTime(date).ToString("dd-MMMM-yyyy");
            var query = "select * from flight where lower(Origin) = " + "\'" + model.Origin.ToLower() + "\'" + " and lower(Destination) = " + "\'" + model.Destination.ToLower() + "\'" +" and Startdatetime between dateadd(day, -1, " + "\'" + dateInput + "\'" + ") and dateadd(day, 1, " + "\'" + dateInput + "\'" + ")" +" order by Layoverdatetime";
            var res = ctx.Database.SqlQuery<Flight>(query).ToList<Flight>();
            return View(res);
        }
        
    }
}

ATRS/Controllers/ReservationController.cs
using ATRS.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATRS.Controllers
{
    public class ReservationController : Controller
    {
        atrsEntities ctx = new atrsEntities();
        public ActionResult Reservations() 
        {
            var res = ctx.Database.SqlQuery<Reservation>("select * from Reservation").ToList<Reservation>();
            return View(res);
        }
        // GET: Reservation
        public ActionResult Book(Flight fDetials)
        {
            TempData["FlightNumber"] = fDetials.FlightNumber;
            TempData["FlightOrigin"] = fDetials.Origin;
            TempData["FlightDestination"] = fDetials.Destination;
            TempData["Layover"] = fDetials.Layover;
            var query = "select * from passenger";
            var res = ctx.Database.SqlQuery<Passenger>(query).ToList<Passenger>();
            return View(res);
        }

        [HttpPost]
        public ActionResult ConfirmBooking(FormCollection form) 
        {
            string flightNumber = form["FlightNumber"];
            string PassengerID = form["PassengerID"];
            string Ticket = form["Ticket"];
            var res = ctx.Database.SqlQuery<Reservation>("select * from Reservation order by ReservationNumber desc").ToList<Reservation>();
            var reservationID = res[0].ReservationNumber;
            reservationID += 1;
            var queryToReservation = ("insert into Reservation(ReservationNumber, PassengerID, Ticket, FlightNumber) values(" + reservationID + ",\'" + PassengerID + "\'," + "\'" + Ticket + "\'," + "\'" + flightNumber + "\')");
            ctx.Database.ExecuteSqlCommand(queryToReservation);
            ctx.SaveChanges();
            var resUpdated = ctx.Database.SqlQuery<Reservation>("select * from Reservation").ToList<Reservation>();
            return View("Reservations", resUpdated);
        }
    }
}

ATRS/Views/Flight/FlightList.cshtml
@model List<ATRS.Context.Flight>
@{
    ViewBag.Title = "FlightList";
}

<h2>FlightList</h2>

<table class="table table-hover">
    <tr>
        <th>Flight No</th>
        <th>Aircraft</th>
        <th>Source</th>
        <th>Layover</th>
        <th>Destination</th>
        <th>Airline</th>
        <th>Start</th>
        <th>End</th>
    </tr>
    
    @foreach (var item in Model)
    {
       <tr>
            <td>@item.FlightNumber</td>
            <td>@item.Aircraft</td>
            <td>@item.Origin</td>
            <th>@item.Layover || @item.Layoverdatetime</th>  
            <td>@item.Destination</td>
            <td>@item.Airline</td>
            <td>@item.Startdatetime</td>
            <td>@item.Enddatetime</td>
            <td>
                <a href="@Url.Action("Book","Reservation", new { item.FlightNumber, item.Origin, item.Destination , item.Layover })" class="btn btn-success">Book</a>
            </td>
       </tr>
    }

</table>

ATRS/Views/Flight/FlightSearch.cshtml
@model ATRS.Context.Flight
@{
    ViewBag.Title = "FlightSearch";
}

<h2>FlightSearch</h2>

@using (Html.BeginForm("FlightList", "Flight", FormMethod.Post)) 
{ 
<div class="container">
    <div class="form-group">
        <label>Source</label>
        @Html.TextBoxFor(x => x.Origin, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Destination</label>
        @Html.TextBoxFor(x => x.Destination, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Date of Travel</label>
        @Html.TextBoxFor(x => x.Startdatetime, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Search</button>
    </div>
</div>
}